import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { LightRays } from "@/components/light-rays";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const localization = {
  unstable__errors: {
    passwordComplexity: {
      sentencePrefix: 'Oops! Your password must contain',
    },
  },

  signUp: {
    start: {
      title: "Join {{applicationName}} today!",
      subtitle: 'Create your account using one of the options below',
      
    },
    emailCode: {
      subtitle: 'We just sent a code to your email. Enter it below.',
    },
    
  },

  lastAuthenticationStrategy: 'Last Used',

  signIn: {
    start: {
      title: "Welcome back to {{applicationName}}!",
      subtitle: 'Use one of the options below to access your account',
    },
  },
}

export const metadata: Metadata = {
  title: "Veridion Studios - Passport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider localization={localization}>
          <div style={{ position: 'relative' }}>
            <div style={{ position: 'absolute', inset: 0, zIndex: 1, pointerEvents: 'none' }}>
              <LightRays />
            </div>
            <div style={{ position: 'relative', zIndex: 2 }}>
              {children}
            </div>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
